# Generated by Django 2.2.3 on 2019-08-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvemmusicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='Alternative Rock', max_length=150),
        ),
    ]
